version: '3.9'
services:
  wordpress:
    expose:
      - 9000
      - 9003
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=172.28.80.1
      # This should correspond to the server declared in PHPStorm `Preferences | Languages & Frameworks | PHP | Servers`
      # Then PHPStorm will use the corresponding path mappings
      PHP_IDE_CONFIG: serverName=${NGINX_PROJECT}.${NGINX_HOST}

