version: '3.9'
services:

  wordpress:
    # default port 9000 (FastCGI)
    image: wordpress:5-fpm
    build:
      context: docker/wordpress
      dockerfile: docker-wordpress
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${WORDPRESS_WP_CONTENT}:/var/www/html/wp-content
      - ${WORDPRESS_UPLOADS_CONFIG}:/usr/local/etc/php/conf.d/uploads.ini
      - ${WORDPRESS_PHP_CONFIG}:/usr/local/etc/php/conf.d/php.ini
      
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}

  database:
    # default port 3306
    image: mysql:8
    ports:
      - "3306:3306"    # http
    env_file:
      - .env
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./:/app/
      - db:/var/lib/mysql
    command:
      - '--default-authentication-plugin=mysql_native_password'

  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:1
    environment:
      FPM_ENTRYPOINT: index
      PHP_FPM_CONTAINER: wordpress
      NGINX_PROJECT: ${NGINX_PROJECT}
      NGINX_HOST: ${NGINX_HOST}
    ports:
      # HTTP
      - target: 80
        published: 80
        protocol: tcp
      # HTTPS
      - target: 443
        published: 443
        protocol: tcp
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - wordpress
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf:ro
      - ${NGINX_SSL_CERTS}:/etc/ssl:ro
      - ${NGINX_LOGS}:/var/log/nginx

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: unless-stopped
    depends_on:
      - database

volumes:
  db: